[env]
EDITOR = "code --wait"
NODE_OPTIONS = ""
NODE_ENV = "development"
#
mise.file = ".env" # load vars from a dotenv file
_.path = [
  # adds an absolute path
  "~/.local/share/bin",
  # adds paths relative to directory in which this file was found (see below for details), not PWD
  "{{config_root}}/node_modules/.bin",
  # adds paths relative to the exact file that this is found in (not PWD)
  "tools/bin",
]

[tools]
act = "0.2.82"
bats = "1.12.0"
node = "23.11.1"
usage = "2.3.2"
yarn = "4.8.1"
yq = "4.47.2"
shfmt = "latest"
shellcheck = "0.11.0"
action-validator = "0.5.4"
direnv = "2.37.1"
"ubi:trufflesecurity/trufflehog" = "v3.90.8"
"ubi:moonrepo/moon" = "1.41.2"
"go:oss.terrastruct.com/d2" = "latest"
