#!/usr/bin/env bash

#MISE description="Builds the site"
#MISE depends=["content", "typecheck"]
#MISE sources=["./app/**/*", "./content/**/*"]
#MISE outputs=["./dist/**/*"]

yarn remix vite:build

mise run generate
