#!/usr/bin/env bash
#MISE description="Builds the site"
#MISE depends=["content", "typecheck"]
#MISE sources=["./app/**/*", "./content/**/*"]
#MISE outputs=["./dist/**/*"]

yarn remix vite:build

yarn tsx ./ssg-cli.ts \
    --build ./build/server/index.js \
    --output ./dist

cp -r ./build/client/* ./dist
