#!/usr/bin/env bash

# https://usage.jdx.dev/
#USAGE flag "-w --watch" help="Run in watch mode"

#MISE description="Prepares content for building the site"
#MISE depends=["content"]
#MISE sources=["./content/**/*"]
#MISE outputs=[".content-collections/**/*"]

# - global
# shellcheck disable=SC2154
if [ "$usage_watch" = "true" ]; then
    yarn content-collections watch
else
    yarn content-collections build
fi
