#!/usr/bin/env bash
#MISE depends=["content", "build", "typecheck"]
# https://usage.jdx.dev/
#USAGE flag "-c --configuration <configuration>" help="Build with the specified configuration" {
#USAGE   choices "production" "development" "preview" "localproduction" "localdevelopment" "localpreview"
#USAGE }

current_branch=$(git branch --show-current)

echo "Deploying with configuration: ${usage_configuration}"
echo "Current branch: ${current_branch}"

if [ -z "${usage_configuration}" ]; then
    echo "No configuration specified"
    exit 1
fi

if [ "${usage_configuration}" == "production" ]; then
    wrangler pages deploy dist --branch main --project-name zenobius
fi

if [ "${usage_configuration}" == "development" ]; then
    wrangler pages deploy dist --branch develop --project-name zenobius
fi

if [ "${usage_configuration}" == "preview" ]; then
    wrangler pages deploy dist --branch="${current_branch}" --project-name zenobius
fi

if [ "${usage_configuration}" == "localproduction" ]; then
    gopass env cloudflare/zenobius wrangler pages deploy dist --branch main --project-name zenobius
fi

if [ "${usage_configuration}" == "localdevelopment" ]; then
    gopass env cloudflare/zenobius wrangler pages deploy dist --branch develop --project-name zenobius
fi

if [ "${usage_configuration}" == "localpreview" ]; then
    gopass env cloudflare/zenobius wrangler pages deploy dist --branch="${current_branch}" --project-name zenobius
fi
