#!/usr/bin/env bash

. ".mise/helpers.sh"

#USAGE flag "-t --title" description="The title of the new post"

slugify() {
    echo "${@}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-'
}

create_new_post() {

    local title
    local date

    title="${1}"
    date=$(date +"%Y-%m-%d")

    template_context="{\"Date\":\"$(date +"%Y-%m-%d")\",\"Title\":\"${title}\"}"
    file_template='"content/posts/\(.Date)-\(.Title | gsub(" ";"-") | ascii_downcase).md"'
    filepath=$(template "$file_template" "${template_context}")

    dedent """
        ---
        date: ${date}
        title: ${title}
        draft: true
        filepath: ${filepath}
        ---
    """ >"${filepath}"

}

title="$(arg_or_prompt "Enter the title of the post" "${usage_title}")"
create_new_post "$title"
