#!/usr/bin/env bash

#MISE description="Run typechecking on the project"
#MISE depends=["content"]
#MISE sources=["./app/**/*"]
#MISE outputs=["tsconfig.tsbuildinfo", "tsconfig.app.tsbuildinfo"]

tsc -p ./tsconfig.app.json --noEmit --incremental
