name: Pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@63a673876c7072c1d6ecb2049c0d572976c83b22 # v2
        with:
          version: 2024.11.4

      - name: Install Node Modules
        uses: ./.github/actions/setup-yarn

      - name: Lint, Test, Build, Typecheck
        run: |
          mise task run content
          mise task run typecheck
          mise task run lint
          mise task run build

      - name: Comment
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c #v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: preview-deployment-url
          message: 'Preview deployment started'

      - name: Deploy to Preview
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          mise task run deploy --configuration=preview |
            .github/scripts/extract-cloudflare-deployment-urls.sh \
              github_output "$GITHUB_OUTPUT"

      - name: Comment
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c #v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: preview-deployment-url
          message: |
            Preview deployment complete

            URL: ${{ steps.deploy.outputs.url }}
            ALIAS_URL: ${{ steps.deploy.outputs.alias_url }}
          recreate: true
