name: Pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write
  actions: read
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2
        env:
          GITHUB_API_TOKEN: ${{ secrets.ASDF_GITHUB_API_TOKEN }}
        with:
          version: 2024.11.4

      - name: Install Node Modules
        uses: ./.github/actions/setup-yarn

      - name: Lint, Test, Typecheck
        run: |
          mise task run content
          mise task run typecheck
          mise task run lint

      - name: Build
        run: |
          mise task run build

      - name: E2E Tests
        run: |
          mise task run e2e --reporter=json --output=results.json

      - uses: daun/playwright-report-summary@e542390160d927152b739167a40b4be6a0bdfda2 # v3
        if: always()
        with:
          report-file: results.json

      - name: Upload E2E Report
        if: always()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # 4.6.0
        with:
          name: build
          path: playwright-report

      - name: Comment
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c #v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: preview-deployment-url
          message: 'Preview deployment started'

      - name: Deploy to Preview
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          mise task run deploy --configuration=preview |
            .github/scripts/extract-cloudflare-deployment-urls.sh \
              github_output "$GITHUB_OUTPUT"

      - name: Comment
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c #v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: preview-deployment-url
          message: |
            Preview deployment complete

            URL: ${{ steps.deploy.outputs.url }}
            ALIAS_URL: ${{ steps.deploy.outputs.alias_url }}
          recreate: true
