name: Sync labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
        with:
          sparse-checkout: .github/labels.yml

      - uses: EndBug/label-sync@4227d8db349126b59efdbebf7842b032f4fe430a #v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
